; vim: set ft=dosini:

# TODO: test that this still works after extracting secrets
#       if not, merge in ~/.odbc.secrets.ini

; for po forecaster
[pwrdta]
Description      = Retalix
Trace            = No
Database         = FFPRDATL
Port             = 8471
DefaultLibraries = PWRDTA
Driver           = IBM i Access ODBC Driver
Conntype         = 2
System           = replaceme
UserID           = replaceme
Password         = replaceme

[pwrbuyd]
Description      = Retalix
Trace            = No
Database         = FFPRDATL
Port             = 8471
DefaultLibraries = PWRBUYD
Driver           = IBM i Access ODBC Driver
Conntype         = 2
System           = replaceme
UserID           = replaceme
Password         = replaceme

; for commission reporer, same as pwrdta
; TODO: update commission reporter to accept multiple odbc libraries
[retalix]
Description      = Retalix
Trace            = No
Database         = FFPRDATL
Port             = 8471
DefaultLibraries = PWRDTA
Driver           = IBM i Access ODBC Driver
Conntype         = 2
System           = replaceme
UserID           = replaceme
Password         = replaceme

[super8_test]
Driver = SQLite3
Database = /Users/john/Developer/Super8/super8/db/super8_test.db
Timeout = 2000

!Include /Users/john/.odbc.secrets.ini
