; vim: set ft=dosini:

[pwrdta]
Description      = Retalix
Trace            = No
System           = ***REMOVED***
Database         = FFPRDATL
Port             = 8471
DefaultLibraries = PWRDTA
UserID           = ***REMOVED***
Password         = ***REMOVED***
Driver           = IBM i Access ODBC Driver
Conntype         = 2

[pwrbuyd]
Description      = Retalix
Trace            = No
System           = ***REMOVED***
Database         = FFPRDATL
Port             = 8471
DefaultLibraries = PWRBUYD
UserID           = ***REMOVED***
Password         = ***REMOVED***
Driver           = IBM i Access ODBC Driver
Conntype         = 2

; for commission reporer, same as pwrdta
; TODO: update commission reporter to accept multiple odbc libraries
[retalix]
Description      = Retalix
Trace            = No
System           = ***REMOVED***
Database         = FFPRDATL
Port             = 8471
DefaultLibraries = PWRDTA
UserID           = ***REMOVED***
Password         = ***REMOVED***
Driver           = IBM i Access ODBC Driver
Conntype         = 2

[super8_test]
Driver = SQLite3
Database = /Users/john/Developer/Super8/super8/db/super8_test.db
Timeout = 2000
