#!/usr/bin/env zsh

alias g='git'
alias gvim='vimr'
alias ll='ls -l'
alias q='exit'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias yt='yt-dlp --no-mtime --format 22 -o "%(uploader)s • %(title)s.%(ext)s" "`pbpaste`"' # download youtube URL on clipboard

# shadowed
alias cat='ccat' # syntax-highlighted cat output
alias ctags="`brew --prefix`/bin/ctags"

# default args/env
alias bc='bc --mathlib --quiet'
alias ls='ls -FG'
alias serve='serve -c /Users/john/Developer/serve.json -l tcp://0.0.0.0:5000'
alias ssh='TERM=xterm-256color ssh'
alias tree='tree -C'

# tools
alias json='python -m json.tool' # pretty-print json
alias showpath='echo $PATH | tr ":" "\n"'
alias speedtest='curl -o /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias commit-and-submit='lein test && git add . && git commit && git push && exercism submit src/*'

# gradescope
# alias vup='vagrant up'
# alias vsh='vagrant ssh'
# alias vsync='vagrant gatling-rsync-auto'
# alias vhalt='vagrant halt && exit'
# alias waitsh='sleep 25 && vagrant ssh'
# alias annotate='bundle exec annotate'

# rails
alias rails='bin/rails'
alias rspec='bin/rspec'
alias rake='bin/rake'
alias annotate='bundle exec annotate'
