#!/usr/bin/env zsh

alias be='bundle exec'
alias dog='ccat'
alias g='git'
alias gvim='vimr'
alias ll='ls -l'
alias q='exit'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# default args
alias bc='bc --mathlib --quiet'
alias ls='ls -FG'

# homebrew
alias ctags="`brew --prefix`/bin/ctags"

# tools
alias json='python -m json.tool'
alias showpath='echo $PATH | tr ":" "\n"'
alias speedtest='curl -o /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias commit-and-submit='lein test && git add . && git commit && git push && exercism submit src/*'

# gradescope
# alias vup='vagrant up'
# alias vsh='vagrant ssh'
# alias vsync='vagrant gatling-rsync-auto'
# alias vhalt='vagrant halt && exit'
# alias waitsh='sleep 25 && vagrant ssh'
# alias annotate='bundle exec annotate'
alias annotate='bundle exec annotate'
