#!/usr/bin/env bash

## ==== BEFORE ================================================================================
##
##  Back up
##    Messages
##    iBooks
##    Dotfiles (ssh, vim, rails, zsh) (be sure to know the ssh private key password)
##    Little Snitch   (export from app)
##    Chrome          (export from app)
##    Keychain        ~/Library/Keychains
##    Fonts           ~/Library/Fonts ~/Library/FontCollections
##    Atom            ~/.atom/snippets.cson
##    NValt           ~/Library/Application\ Support/Notational\ Data
##
##  Skip
##    Transmit (to restore: copy sqlite from dropbox & remove any xml)
##    Things (Things Cloud)
##    Sublime Text (license in Gmail)
##    OmniOutliner (license in 1Password)
##    GoToAssist (license in Napoli mail?)
##    Safari (bookmarks in iCloud)
##
## ==== AFTER ================================================================================
##
##  App Store
##    Coda
##    DaisyDisk
##    Disk Diet
##    Growl
##    Slack
##    YemuZip
##
##  Other stuff
##    AudioMonitor (MTCoreAudio)
##    Retina DisplayMenu -- https://dl.dropbox.com/u/87351306/RDM.tar.gz
##    Finale
##    Adobe
##    Printer
##
## ================================================================================================


formulas=(
  ansible
  coreutils
  curl
  findutils
  git
  htop-osx
  hub
  imagemagick
  openssh
  openssl
  node
  parallel
  postgresql
  readline
  rename
  sqlite
  the_silver_searcher
  tig
  trash
  tree
  unrar
  vim
  wget
  youtube-dl
  z
  zsh
  zsh-completions
)

applications=(
  1password
  alfred
  # atom
  audacity
  colors
  cord
  dosbox
  dropbox
  eclipse-java
  flash
  flux
  front
  github-desktop
  gitx
  icecat
  iterm2
  java
  karabiner
  libreoffice
  little-snitch
  macdown
  macvim
  menubar-countdown
  nosleep
  nvalt
  omnioutliner
  recordit
  seil
  skype
  spotify
  steam
  sublime-text
  things
  tiled
  transmission
  transmit
  vagrant
  virtualbox
  vlc
  xquartz
)

fonts=(
  font-lato
  font-lobster
  font-fira-code
)

quicklook_plugins=(
  betterzipql
  qlcolorcode
  qlmarkdown
  qlstephen # for files with no extension
  quicklook-csv
  quicklook-json
)

benched=(
  avidemux
  broomstick
  ccleaner
  ffmpegx
  file-juicer
  google-chrome # updates frequently
  handbrake
  kaleidoscope # time-limited trial
  mactex # too big
  mysqlworkbench
  perian
  pgadmin3
  postbox # auto-updates
  pycharm-pro
  silverlight
  the-unarchiver
)

# atom_packages=(
#   atom-beautify
#   file-icons
#   indent-guide-improved
#   js-refactor
#   language-cjsx
#   language-ejs
#   language-haml
#   language-slim
#   linter
#   linter-eslint
#   linter-jshint
#   linter-ruby
#   react
#   todo-show
# )

ruby_gems=(
  rails
  rubocop
  listen # work
)


## XCode Tools
xcode-select --install

## Homebrew & Homebrew Cask
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install caskroom/cask/brew-cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
brew tap caskroom/fonts

## Ruby & rbenv
brew install rbenv ruby-build ## add eval "$(rbenv init -)" to profile once zsh is installed
rbenv install 2.2.3
gem install rails

## Libraries & Tools
brew install ${formulas[@]}
##   to enable zsh:
##   1. add /usr/local/bin/zsh to /etc/shells
##   2. run chsh -s $(which zsh)
##
##   to enable zsh-completions:
##   1. add fpath=(/usr/local/share/zsh-completions $fpath) to ~/.zshrc
##   2. run rm -f ~/.zcompdump; compinit

## OSX Applications, Fonts, Quicklook Plugins
brew cask install ${applications[@]}
brew cask install ${fonts[@]}
brew cask install ${quicklook_plugins[@]}

## Atom Plugins
# apm uninstall metrics
# apm install ${atom_packages[@]}

## Ruby Gems
gem install ${ruby_gems[@]}

## Work
vagrant plugin install vagrant-gatling-rsync

## Clean
gem cleanup
brew cleanup
brew cask cleanup
rm -rf $(brew --cache)'/*'

## Download Terminal colors (add to iTerm in-app)
wget https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Chalkboard.itermcolors -P ~/Downloads
