srgb = true

[font]
size = 14
hinting = "full"
edging = "subpixelantialias"

[[font.normal]]
family = "Dank Mono"
style = "Light"

[[font.bold]]
family = "Dank Mono"
style = "Bold"

[[font.italic]]
family = "Dank Mono"
style = "Light Italic"

[[font.bolditalic]]
family = "Dank Mono"
style = "Bold Italic"
